apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: influxdb
  namespace: monitoring
spec:
  interval: 1m
  url: https://helm.influxdata.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: botkube
      version: 4.8.6
      sourceRef:
        kind: HelmRepository
        name: influxdb
        namespace: monitoring
      interval: 1m
  values:
    image:
      repository: "influxdb"
      tag: "1.8.3"
    service:
      type: LoadBalancer
    persistence:
      enabled: true
      size: 50Gi
      storageClass: longhorn
    resources:
      requests:
        memory: 2000Mi
        cpu: 100m
      limits:
        memory: 4000Mi
    livenessProbe:
      timeoutSeconds: 10
    readinessProbe:
      timeoutSeconds: 10
    startupProbe:
      enabled: true
      failureThreshold: 6
      periodSeconds: 5
    config:
      opentsdb:
        enabled: true