apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: botkube
  namespace: monitoring
spec:
  interval: 5m
  url: https://infracloudio.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: botkube
      version: v0.11.0
      sourceRef:
        kind: HelmRepository
        name: botkube
        namespace: monitoring
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: slack-token
      valuesKey: token
      targetPath: communications.slack.token
  values:
    image:
      repository: infracloudio/botkube
      tag: v0.10.0
    #serviceMonitor:
    #  enabled: true
    communications:
      slack:
        enabled: true
        channel: 'k8s'
        notiftype: short
    config:
      settings:
        clustername: olympus
      resources:
        - name: pod                # Name of the resources e.g pod, deployment, ingress, etc. (Resource name must be in singular form)
          namespaces:
            include:
              - all
            ignore:                 # List of namespaces to be ignored (omitempty), used only with include: all
              - rook-ceph                    # example : include [all], ignore [x,y,z]
              - kube-system
          events:                   # List of lifecycle events you want to receive, e.g create, update, delete, error OR all
            - create
            - delete
        - name: service
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: deployment
          namespaces:
            include:
              - all
          events:
            - create
            - update
            - delete
            - error
          updateSetting:
            includeDiff: true
            fields:
              - spec.template.spec.containers[*].image
        - name: statefulset
          namespaces:
            include:
              - all
          events:
            - create
            - update
            - delete
            - error
          updateSetting:
            includeDiff: true
            fields:
              - spec.template.spec.containers[*].image
        - name: ingress
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: node
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: namespace
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: persistentvolume
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: persistentvolumeclaim
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: secret
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: configmap
          namespaces:
            include:
              - all
            ignore:
              - rook-ceph
          events:
            - delete
            - error
        - name: daemonset
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
            - update
          updateSetting:
            includeDiff: true
            fields:
              - spec.template.spec.containers[*].image
        - name: job
          namespaces:
            include:
              - all
            ignore:
              - rook-ceph
              - kube-system
          events:
            - create
            - update
            - delete
            - error
          updateSetting:
            includeDiff: true
            fields:
              - spec.template.spec.containers[*].image
              - status.conditions[*].type
        - name: role
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: rolebinding
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: clusterrole
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: clusterrolebinding
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error