apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  values:
    controller:
      service:
        type: LoadBalancer
        loadBalancerIP: 10.0.60.21
        externalTrafficPolicy: Local