apiVersion: v1
kind: ConfigMap
metadata:
  namespace: networking
  name: metallb-config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.0.60.21-10.0.60.25