apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: helm-release
  namespace: gotk-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: '*'
      namespace: rook-ceph
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: error
  namespace: gotk-system
spec:
  providerRef:
    name: slack
  eventSeverity: error
  eventSources:
    - kind: HelmRepository
      name: '*'
