apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: rook-ceph
  namespace: gotk-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: '*'
      namespace: rook-ceph