---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 1m
  url: https://releases.rancher.com/server-charts/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 1m
  chart:
    spec:
      chart: rancher
      version: 2.4.8
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: cattle-system
      interval: 1m
  values:
    hostname: rancher.itstoni.com
    ingress:
      tls:
        source: secret